name: Build app

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: '^18.18.0 || >=20.0.0'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: yarn install --no-frozen-lockfile

      - name: Build app
        run: yarn build
